name: sharpvendor
description: "Vendor App For Go Sharp Sharp LTD."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_image_compress: ^2.4.0
  skeletonizer: ^2.1.0+1
  dotted_border: ^3.1.0
  flutter_dotenv: ^5.1.0
  get_storage: ^2.1.1
  upgrader:
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.4.0
  dotted_line: ^3.2.3
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player:
  vibration: ^3.1.3
  lottie: ^3.1.3
  pinput: ^5.0.1
  flutter_svg: ^2.0.10+1
  dio: ^5.4.0
  fl_chart: ^1.0.0
  get_it: ^8.2.0
  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  flutter_google_maps_webservices: ^1.1.1
  image_picker: ^1.1.2
  webview_flutter: ^4.8.0
  image_cropper: ^9.1.0
  intl_phone_field: ^3.1.0
  flutter_polyline_points: ^3.0.1
  cloudinary: ^1.2.0
  socket_io_client: ^3.0.2
  flutter_native_splash: ^2.4.6
  intl:
  cupertino_icons: ^1.0.8
  zego_uikit_prebuilt_call: ^4.16.21
  zego_uikit_signaling_plugin: ^2.8.9
  zego_express_engine:
  zego_zim: ^2.20.0+1
  zego_zpns: ^2.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.14.1
  wakelock_plus: ^1.2.2

  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/icons/
    - assets/imgs/
    - assets/json/


  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:*
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_native_splash:
  color: "#000000"
  image: "assets/icons/gosharp_icon.png"
  android: true
  ios: true
  web: false
  android_12:
    color: "#000000"
    image: "assets/icons/gosharp_icon.png"